# local path

dataset_path: '/home/wan/Documents/projects/data/test_lmd'
#lpd_path : 'home/wan/Documents/projects/musegan/test_lpd'
result_path: '/home/wan/Documents/projects/data_processed/test_lmd_processed'


# parameters
beat_resolution: 4
multicore: 30
link_to_msd: True
