# local path

dataset_path: '/tmp/jrw8217/data/bach/cantatas'
#dataset_path : '/home/wan/Documents/projects/data/test_chord'
result_path: '/tmp/jrw8217/data/bach_processed'
#result_path : '/home/wan/Documents/projects/data_preprocessed/test_chord_preprocessed'


# parameters
beat_resolution: 4
multicore: 15
link_to_msd: False
