# local path
dataset_path: '/home/wan/Documents/projects/musegan/test_lmd/'
#lpd_path : 'home/wan/Documents/projects/musegan/test_lpd'
result_path: '/home/wan/Documents/projects/musegan/test_lpd/'

# parameters
beat_resolution: 4
multicore: 1
link_to_msd: True
