# local path

dataset_path: '/data1/lakh/lmd_full'
#other path : 'home/wan/Documents/projects/data/test_lmd'
result_path: '/data1/lakh/lmd_full_processed_ckey'
#other path : '/home/wan/Documents/projects/data_processed/test_lmd_processed'

# parameters
beat_resolution: 4
multicore: 30
link_to_msd: True
