# local path

dataset_path: '/data1/lakh/test_melody'
#dataset_path : '/home/wan/PycharmProjects/test/test1/debug'
result_path: '/data1/lakh/test_melody_processed'
#result_path : '/home/wan/Documents/projects/data_processed/debugging'

# parameters
beat_resolution: 4
multicore: 1
link_to_msd: False
