# local path

dataset_path: '/data1/lakh/lmd_full'
#dataset_path : '/home/wan/Documents/projects/data/pianoroll_test'
result_path: '/data1/lakh/new_lmd_full_processed_nonbinary_rmsm'
#result_path : '/home/wan/Documents/projects/data_processed/pianoroll_test2'


# parameters
beat_resolution: 4
multicore: 15
link_to_msd: False
