# local path

dataset_path: '/data1/lakh/CGAmF'
#dataset_path : '/home/wan/PycharmProjects/test/test1/CGAmF'
result_path: '/data1/lakh/CGAmF_preprocessed'
#result_path : '/home/wan/Documents/projects/data_processed/CGAmF_preprocessed'


# parameters
beat_resolution: 4
multicore: 1
link_to_msd: False
