# local path
dataset_path: '/home/wan/Documents/projects/musegan/test_lmd/'
result_path: '/home/wan/Documents/projects/musegan/test_lpd/'

# parameters
beat_resolution: 4
multicore: 16
link_to_msd: True
